#!/bin/bash

clear

echo "Los comandos son los siguientes:"
	echo ""
	echo "arbol:"      
	echo "Muestra de manera gráfica la jerarquía de un directorio que se le especifique al comando. Si al comando no se le específica directorio, el comando se ejecuta sobre el directorio actual"
	echo "Es importante indicar el directorio donde se realizara el arbol"
	echo ""
	echo "ayuda:"       
 	echo "Da información acerca de los comandos y respecto al uso de la Terminal"
	echo ""
	echo "infosis:"
	echo "Muestra información sobre el sistema donde se está ejecutando la terminal"
	echo ""
	echo "fecha:"
	echo "Muestra la fecha actual"
	echo ""
	echo "hora:"        
	echo "Muestra la hora actual"
	echo ""
	echo "creditos:"    
	echo "Muestra los créditos de los programadores"
	echo ""
	echo "gato:"        
	echo "Juego para dos de gato"
	echo ""
	echo "ahorcado:"     
	echo "Juego de ahorcado"
	echo ""
	echo "limpia:"     
	echo "Limpia la consola"
	echo ""
	echo "buscar:"     
	echo "buscara un archivo que indiques en el directorio que indiques"
	echo ""
	echo "reproductor:" 
	echo "Ejecuta un reproductor mp3"
	echo ""
	echo "Si desea salir del programa ejecute el comando \"salir\""